config/routes.rb
Rails.application.routes.draw do
  resources :results
  resources :tests
  resources :answers
  resources :questions
  resources :coincidences
  resources :articles
  resources :animals
  resources :articlecats
  resources :animalcats
  #devise_for :users
  #resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users_admin, :controller => 'users'
 

 devise_for :users,controllers: { registrations: "registrations", sessions: "sessions"}

 #put '/users_admin/:id/edit' => 'users#update' ,:as => :users_edit

 patch 'users_admin/:id/edit' => 'users#update' , as: 'users_edit'

 get '/animalcats/:id/showAnimalsCat' => 'animalcats#showAnimalsCat', as: 'showAnimalsCat'
  
get '/articlecats/:id/showArticlesCat' => 'articlecats#showArticlesCat', as: 'showArticlesCat'



# se agrega esta linea para que siempre lo mande al login cado no esté resgistrado
authenticated :user do
   root :to => "users#index"
 end
 root :to => redirect("/users/sign_in")
end

app/models/animal.rb
class Animal < ApplicationRecord
	has_many :coincidences
	belongs_to :animalcat 
	has_many :articles 
	has_many :tests
end

app/models/animalcat.rb
class Animalcat < ApplicationRecord
	has_many :animals
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question
	has_many :results
	has_many :tests, through: :results
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :animal
	belongs_to :articlecat
end

app/models/articlecat.rb
class Articlecat < ApplicationRecord
	has_many :articles
end

app/models/coincidence.rb
class Coincidence < ApplicationRecord
	belongs_to :animal
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :answers
end

app/models/result.rb
class Result < ApplicationRecord
	belongs_to :test
	belongs_to :answer
end

app/models/test.rb
class Test < ApplicationRecord
	belongs_to :animal
	belongs_to :user
	has_many :results
	has_many :answers, through: :results
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tests
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        #format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.html { redirect_to users_admin_index_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email,:name, :lastName, :phone, :typeu, :street, :exterior_number, :interior_number, :city, :state, :zip)
    end
end

app/helpers/animalcats_helper.rb
module AnimalcatsHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articlecats_helper.rb
module ArticlecatsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/coincidences_helper.rb
module CoincidencesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, url: users_edit_path(user)) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :lastName %>
    <%= form.text_field :lastName, id: :user_lastName %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :user_phone %>
  </div>

  <div class="field">
    <%= form.label :typeu %>
    <%= form.number_field :typeu, id: :user_typeu %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street, id: :user_street %>
  </div>

  <div class="field">
    <%= form.label :exterior_number %>
    <%= form.text_field :exterior_number, id: :user_exterior_number %>
  </div>

  <div class="field">
    <%= form.label :interior_number %>
    <%= form.text_field :interior_number, id: :user_interior_number %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :user_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :user_state %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip, id: :user_zip %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', users_admin_path(@user) %> |
<%= link_to 'Back', users_admin_index_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Phone</th>
      <th>Typeu</th>
      <th>Street</th>
      <th>Exterior number</th>
      <th>Interior number</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.lastName %></td>
        <td><%= user.phone %></td>
        <td><%= user.typeu %></td>
        <td><%= user.street %></td>
        <td><%= user.exterior_number %></td>
        <td><%= user.interior_number %></td>
        <td><%= user.city %></td>
        <td><%= user.state %></td>
        <td><%= user.zip %></td>
        <td><%= user.email %></td> 
        <td><%= link_to 'Show', users_admin_path(user)%></td>
        <td><%= link_to 'Edit', edit_users_admin_path(user) %></td>
        <td><%= link_to 'Destroy', users_admin_index_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_users_admin_path %>
<%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link", ) %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastName %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Typeu:</strong>
  <%= @user.typeu %>
</p>

<p>
  <strong>Street:</strong>
  <%= @user.street %>
</p>

<p>
  <strong>Exterior number:</strong>
  <%= @user.exterior_number %>
</p>

<p>
  <strong>Interior number:</strong>
  <%= @user.interior_number %>
</p>

<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @user.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @user.zip %>
</p>

<%= link_to 'Edit', edit_users_admin_path(@user) %> |
<%= link_to 'Back', users_admin_index_path %> 